### ISSUE TITLE
Fields 'status' and 'request_header_referer' cause error in some cases

### ISSUE THREAD

**Issue by albertinisg** [rory/apache-log-parser#12]
I've found that in several cases, when the `status` is not a number and/or the `referer` is not between "", returns a "LineDoesntMatchException". 
The example is, I have the following parser (from a combined log):

<pre>
"%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""
</pre>

Then, I have the `access.log` file, containing the following:

<pre>
002:52ee:xxxx::x - - [11/Jun/2014:22:55:45 +0000] "GET /X230_2.51_g2uj10us.iso HTTP/1.1" - 3414853 - "Mozilla/5.0 (X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0"
2002:52ee:xxxx::x - - [11/Jun/2014:22:56:14 +0000] "GET /boot.iso HTTP/1.1" - 195933084 - "Wget/1.14 (linux-gnu)"
2002:52ee:xxxx::x - - [11/Jun/2014:22:34:11 +0000] "GET /release/ HTTP/1.1" 404 981 - "w3m/0.5.3"
</pre>

And none of them works. The first one and second one, because there's no `status` number; `referer` field is not between "" and it affects to all of them.

**Comment by rory** [comment]
I've released 1.6.1 which supports a `-` for the status code.

I'm not sure what to do about the lack of `"` for the Referer. From my understanding of how apache logs work, the fact that you have a `"` in the format string, should mean that there's always a `"` in there. The way the library is written it would be hard to factor this out.

Are you sure the lines with the `-` for Referer were generated when that log format was in effect?

**Comment by albertinisg** [comment]
Hi rory,

Sorry for my late answer. With the new release seems to work fine! Also, after some updates there's no more lack of `"` at my logfiles, so everything is working good now. You can close the issue.

Thanks!
