### ISSUE TITLE
Problem with time_received

### ISSUE THREAD

**Issue by gleblanc1783** [rory/apache-log-parser#9]
Having some trouble with the time_received field (and subsequently user-agent) field not being extracted properly.

Here's what I have (some of the log entry was sanitized)
```
APACHE_COMBINED="%h %v %V %l %u %t %r %>s %b %{Referer}i %{User-agent}i"
```

```
10.1.1.1 T1 blah.foo.com - - [08/Mar/2015:18:06:58 -0400] GET /content_images/3/American-University-in-Cairo-AUC.jpeg.jpg HTTP/1.1 404 344 http://www.google.ie AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36 
```

```
{'status': '404', 'request_header_referer': 'http://www.google.ie', 'remote_user': '-', 'server_name': 'T1', 'request_http_ver': '1.1', 'request_header_user_agent': '', 'request_first_line': '-0400] GET /content_images/3/American-University-in-Cairo-AUC.jpeg.jpg HTTP/1.1', 'remote_logname': '-', 'request_method': 'GET', 'time_received_datetimeobj': datetime.datetime(2015, 3, 8, 18, 6, 58), 'response_bytes_clf': '344', 'server_name2': blah.foo.com', 'request_url': '/content_images/3/American-University-in-Cairo-AUC.jpeg.jpg', 'time_received_isoformat': '2015-03-08T18:06:58', 'remote_host': '10.1.1.1, 'time_received': '[08/Mar/2015:18:06:58'}
```

If you notice the 'time_received' field doesn't contain the Time Zone like it should, the 'request_first_line' contains more than it should and the UA doesn't get parsed out correctly. I was able to take the regex that the module created and make it work manually:

```
(?P<remote_host>.*?)\s(?P<server_name>.*?)\s(?P<server_name2>.*?)\s(?P<remote_logname>.*?)\s(?P<remote_user>.*?)\s(?P<time_received>.*?\])\s(?P<request_first_line>.*?)\s(?P<status>[0-9]+?)\s(?P<response_bytes_clf>(\d+|-))\s(?P<request_header_referer>.*?)\s(?P<request_header_user_agent>.*)
```

But wasn't able to make it work in the code.

Any thoughts?

**Comment by rory** [comment]
Thanks for your bug report. I have fixed the problem by presuming that time is always wrapped in `[` and `]`. In your regex you have that. It should be OK.

For the timezones, I have added functionality that parses out the timezone and includes some new fields, `time_recieved_tz_*` (which is the timezone aware datetime in the specified timezone), and `time_recieved_utc_*` which is a timezone aware datetime in UTC.

For backwards compatibility, I am keeping `time_recieved` as a naive (non-timezone) datetime in the specified timezone (i.e. local time).

This new functionality, and bug fix, is in version 1.5.
